version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate up"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./migrations
  migrate-test:
    aliases:
      - migrate-tests
    desc: "Test migrate up"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./tests/migrations --migrations-table=migrations_test

